apiVersion: apps/v1
kind: Deployment

metadata:
  name: invint

spec:
  replicas: 1

  selector:
    matchLabels:
      app: invint

  template:
    metadata:
      labels:
        app: invint

    spec:
      containers:
      - name: invint

        image: invintellience.azurecr.io/invint:v1

        imagePullPolicy: Always

        envFrom:
        - secretRef:
            name: invint-secrets

        ports:
        - containerPort: 8000
